version: "3.8"

services:
  mysqlDB:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      -  MYSQL_ROOT_PASSWORD=
      -  MYSQL_DATABASE=stationSki
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
  App_Backend:
    image: aziz198/gestion-station-ski:latest
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
    stdin_open: true
    tty: true



volumes:
  database: