services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
  networks:
      - skistation_network
  app:
    depends_on:
      - mysqldb
    image: aziz198/gestion-station-ski:latest
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?&createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  skistation_network:
    driver: bridge
